export const LAYOUT = {
  WINDOW_HEIGHT: 298, // keep sync with backend (constants.rs)
  CONTROL_BAR_HEIGHT: 64,
  CARD_WIDTH: 210,
  CARD_GAP: 24,
  SIDE_PADDING: 20,
  CARD_VERTICAL_PADDING: 12,
};

export const CLIP_LIST_HEIGHT = LAYOUT.WINDOW_HEIGHT - LAYOUT.CONTROL_BAR_HEIGHT;
export const TOTAL_COLUMN_WIDTH = LAYOUT.CARD_WIDTH + LAYOUT.CARD_GAP;
export const PREVIEW_CHAR_LIMIT = 300;
